@host_name=localhost
@port=9990
@host={{host_name}}:{{port}}
@client_id=m2m.client
@scope=bankapi.read
@client_secret=511536EF-F270-4058-80CA-1C89C192F69A
@grant_type=client_credentials
@token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5Q0FDMzI4RjkwOEU2MTQyNTA1RDFCNUQ2NEIxMzQwIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNzE3OTYwNzc1LCJpYXQiOjE3MTc5NjA3NzUsImV4cCI6MTcxNzk2NDM3NSwiYXVkIjpbInByb2R1Y3RhcGkiLCJodHRwczovL2xvY2FsaG9zdDo1MDAxL3Jlc291cmNlcyJdLCJzY29wZSI6WyJwcm9maWxlIiwib3BlbmlkIiwicHJvZHVjdGFwaS5yZWFkIiwicHJvZHVjdGFwaS53cml0ZSJdLCJhbXIiOlsicHdkIl0sImNsaWVudF9pZCI6InByb2R1Y3Qtc3dhZ2dlciIsInN1YiI6Ijg4NDIxMTEzIiwiYXV0aF90aW1lIjoxNzE3OTYwMzI5LCJpZHAiOiJsb2NhbCIsInNpZCI6IjgzNTVBNDMxMjEyODVDQkQyRTM3ODVGMjkwOTU0MjgwIiwianRpIjoiNTcxNENFRDI0MDcxNzY5MEY3QzJFREUyMjc0MTY2QzQifQ.d1tImzckJz814WXhNmR-lGZVs5hiR6aMDsAHR28Y1fqbz4wTomHVwWjh2McBpBfsdTnxdveFzzdrhwk-XMCAqo8TUQ0kPhhikCluoQvu47ybjSgkiPgxCaVo_KFaGaAeSU-B0WIPsTl8rzqXdq-8iEZsD4we--BSCk_fmcInS2eUAJaHAdVGsINrr7T22mGAOIy2lsH1GoU3RaopVJ2w42I1mCUmIt-ZAPBkF9DUy0xfmDdg9U8fOovRuC6hNp9jtW0nSYqdO2xq-pkptb7Ip1rBhB5_rFSPlyGiWaYm78IwLTVrWm5KYKysVWARjWxeZphSJaWf0CHp1IISNLG1UA
###
POST https://{{host}}/identity-api/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

client_id={{client_id}}
&scope={{scope}}
&client_secret={{client_secret}}
&grant_type={{grant_type}}

###
GET https://{{host}}/product-api/v1/product HTTP/1.1
Authorization: bearer {{token}}
Accept: */*

###
POST https://{{host}}/product-api/v1/product HTTP/1.1
Authorization: bearer {{token}}
Accept: */*
Content-Type: application/json

{
    "name": "String",
    "description": "Sting",
    "price": 10
}


### Bank
GET https://{{host}}/bank-api/v1/bank HTTP/1.1
Authorization: bearer {{token}}
Accept: */*